resolver: lts-14.13

packages:
- .

extra-deps: [
            # this needs to be done better
          github-0.22,
          binary-instances-1,
          binary-orphans-1.0.1,
          time-compat-1.9.2.2,
]
